version: "3.4"

services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: src/webapi/Dockerfile
    ports:
      - 80:80
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
